[build]
builder = "DOCKERFILE"
dockerfilePath = "HomeBudget.API/Dockerfile"
dockerContext = "HomeBudget.API"

[deploy]
startCommand = ""
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
